import { ElementRef, IterableDiffers, OnInit, DoCheck } from '@angular/core';
import { FsDatePickerModel } from './../../services/fsdatepickermodel.service';
import { FsDatePickerCommon } from './../../services/fsdatepickercommon.service';
export declare class FsDatepickerRangeComponent implements OnInit, DoCheck {
    fsDatePickerModel: FsDatePickerModel;
    private fsDatePickerCommon;
    element: ElementRef;
    private _iterableDiffers;
    parentInstance: any;
    toDisabledDays: any[];
    toDisabledTimes: any[];
    startCalendarMonth: any;
    endCalendarMonth: any;
    highlightStartDate: any;
    highlightEndDate: any;
    private modelDiffer;
    constructor(fsDatePickerModel: FsDatePickerModel, fsDatePickerCommon: FsDatePickerCommon, element: ElementRef, _iterableDiffers: IterableDiffers);
    ngOnInit(): void;
    ngDoCheck(): void;
    setStartDate(date: any): void;
    setEndDate(date: any): void;
    setStartTime(date: any): void;
    setEndTime(date: any): void;
    setDates(startDate: any, endDate: any): void;
    onDatesChange(data: any): void;
    toDisabledDaysUpdate(startDate: any, endDate: any): void;
    toDisabledTimesUpdate(startDate: any, endDate: any): void;
    setDateModeStart(mode: any): void;
    setDateModeEnd(mode: any): void;
    setComponents(data: any): void;
    calendarsDrawMonth(startDate: any, endDate: any): void;
    startCalendarDrawMonth(date: any): void;
    endCalendarDrawMonth(date: any): void;
    private rangeCalendarsConflict(startDate, endDate);
    hoverCalendar(day: any): void;
    onMouseLeaveCalendar(): void;
    close($event?: any): void;
    documentKeydown(e: any): void;
}
