import { Renderer, ElementRef, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { FsDatepickerDialogFactory } from './fsdatepickerdialogfactory.service';
import { FsUtil } from '@firestitch/common';
export declare class FsDatepickerDirective implements OnInit, OnDestroy {
    private _elementRef;
    private renderer;
    private factoryResolver;
    private viewContainerRef;
    private FsDatepickerDialogFactory;
    private FsUtil;
    hasCalendar: boolean;
    hasDate: boolean;
    minYear: any;
    maxYear: any;
    hasTime: boolean;
    view: string;
    disabledDays: any;
    disabledMinutes: any[];
    disabledHours: any[];
    disabledTimes: any[];
    change$: EventEmitter<any>;
    private _model;
    opened: boolean;
    selected: {};
    yearList: any[];
    private $dialog;
    private rootViewContainer;
    _onTouched: () => void;
    _onChange: (value: any) => void;
    onFocused: (event: any) => void;
    registerOnChange(fn: (value: any) => any): void;
    registerOnTouched(fn: () => any): void;
    constructor(_elementRef: ElementRef, renderer: Renderer, factoryResolver: any, viewContainerRef: any, FsDatepickerDialogFactory: FsDatepickerDialogFactory, FsUtil: FsUtil);
    ngOnInit(): void;
    onChangeInterceptor($event: any): void;
    writeValue(value: any): void;
    getValue(): any;
    private open();
    private inputClick(e);
    inputKeyup(e: any): void;
    inputBlur(event: any): void;
    onWindowResize(event: any): void;
    positionDialog(): void;
    render(input: any): void;
    ngOnDestroy(): void;
}
